<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Processed Payroll Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
        }

        h1 {
            text-align: center;
            color: #1E40AF; /* Blue heading */
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        thead {
            background-color: #1E40AF;
            color: #fff;
        }

        th, td {
            padding: 8px 12px;
            border: 1px solid #ddd;
            text-align: left;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tfoot td {
            font-weight: bold;
            background-color: #f1f5f9;
        }

        .footer {
            text-align: center;
            font-size: 12px;
            color: #555;
            margin-top: 30px;
        }
    </style>
</head>
<body>

    <h1>Processed Payroll Report</h1>

    <table>
        <thead>
            <tr>
                <th>Staff</th>
                <th>Unit</th>
                <th>Department</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Net Salary (Ksh)</th>
                <th>Processed At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payrolls as $pay)
                <tr>
                    <td>{{ $pay->user->name }}</td>
                    <td>{{ $pay->unit->name }}</td>
                    <td>{{ $pay->department->name ?? '-' }}</td>
                    <td>{{ \Carbon\Carbon::parse($pay->start_date)->format('d M Y') }}</td>
                    <td>{{ \Carbon\Carbon::parse($pay->end_date)->format('d M Y') }}</td>
                    <td>{{ number_format($pay->net_salary, 2) }}</td>
                    <td>{{ \Carbon\Carbon::parse($pay->processed_at)->format('d M Y, h:i A') }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align:right;">Total Net Salary:</td>
                <td colspan="2">
                    {{ number_format($payrolls->sum('net_salary'), 2) }}
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by HRMS — {{ date('d M Y') }}
    </div>

</body>
</html>
